export const TYPES = {
    UsersRepository: Symbol.for('UsersRepository'),
    CreateUserUseCase: Symbol.for('CreateUserUseCase'),
    LoginUserUseCase: Symbol.for('LoginUserUseCase'),
    SqliteDatabaseConnection: Symbol.for('SqliteDatabaseConnection'),
    CategoryRepository: Symbol.for('CategoryRepository'),
    PasswordService: Symbol.for('PasswordService'),
    GetRootCategoriesUseCase: Symbol.for('GetRootCategoriesUseCase'),
    GetCategoryTreeUseCase: Symbol.for('GetCategoryTreeUseCase'),
    ProductsRepository: Symbol.for('ProductsRepository'),
    GetDealsOfTheDayUseCase: Symbol.for('GetDealsOfTheDayUseCase'),
    GetFeaturedProductsUseCase: Symbol.for('GetFeaturedProductsUseCase'),
    GetPopularProductsUseCase: Symbol.for('GetPopularProductsUseCase'),
    SearchProductsUseCase: Symbol.for('SearchProductsUseCase'),
    BrandsRepository: Symbol.for('BrandsRepository'),
    SearchBrandsUseCase: Symbol.for('SearchBrandsUseCase'),
    FindBrandByIdUseCase: Symbol.for('FindBrandByIdUseCase'),
    SearchClientFactory: Symbol.for('SearchClientFactory'),
    SearchProductsService: Symbol.for('SearchProductsService'),
    GetPathFromRootUseCase: Symbol.for('GetPathFromRootUseCase'),
    GetImmediateChildrenUseCase: Symbol.for('GetImmediateChildrenUseCase'),
    GetCategoryUseCase: Symbol.for('GetCategoryUseCase'),
    GetByCategoryIdUseCase: Symbol.for('GetByCategoryIdUseCase'),
    GetProductByIdUseCase: Symbol.for('GetProductByIdUseCase')
};
