export enum ExceptionType {
    // Domain exceptions
    AUTHENTICATION_ERROR = 'AUTHENTICATION_ERROR',
    VALIDATION_ERROR = 'VALIDATION_ERROR',
    BUSINESS_RULE_VIOLATION = 'BUSINESS_RULE_VIOLATION',
    ENTITY_NOT_FOUND = 'ENTITY_NOT_FOUND',
    DUPLICATE_ENTITY = 'DUPLICATE_ENTITY',

    // Application exceptions
    UNAUTHORIZED = 'UNAUTHORIZED',
    FORBIDDEN = 'FORBIDDEN',

    // Infrastructure exceptions
    DATABASE_ERROR = 'DATABASE_ERROR',
    EXTERNAL_SERVICE_ERROR = 'EXTERNAL_SERVICE_ERROR',

    // Generic
    INTERNAL_ERROR = 'INTERNAL_ERROR',
}
